# Login
# @name tokenAPI
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "mhurley",
  "password": "secret"
}
###


@authToken = {{tokenAPI.response.body.token}}
# Add Blog
# @name addBlog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Test Blog",
  "author": "TESTER",
  "url": "test.com",
  "likes": 1
}
