POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{$dotenv JWT_TOKEN}}

{
  "title": "Test Blog",
  "author": "Tester",
  "url": "http://example.com",
  "likes": 5
}
